### ISSUE TITLE
require_once

### ISSUE THREAD

**Issue by zuoper** [anselm-urban/HTML5Sites#1]
Warning: require_once(dld89430upsnmUDCX/cms.php) [function.require-once]: failed to open stream: No such file or directory in E:\..\index.php on line 1

**Comment by peternerlich** [comment]
Confirmed, removed it in a local copy already. I am not the owner, I don't know if it had initially a purpose.
This appears in both `index.html` and `advertise/index.html`.

**Comment by zuoper** [comment]
Thanks

**Comment by anselm-urban** [comment]
fixed. it was PHP code from Couch CMS which I tried to implement...
